# Generated by Django 3.2.6 on 2021-09-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('trade_code', models.CharField(max_length=20)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('open', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.IntegerField(null=True)),
            ],
        ),
    ]
