# Generated by Django 3.2.6 on 2021-09-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmarket',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
